fix: Premature delivery stream close
relaycorp/relaynet-cogrpc-jvm pull request #58
Opened 2020-10-16 17:12 UTC by sdsantos

2020-10-17 11:02 UTC, gnarea requested changes
Can you please add 3 tests for the 3 changes you're making here?

2020-10-19 08:28 UTC, gnarea reviewed
BTW, did you test these changes on a real device to ensure this fixes the bug and doesn't introduce regressions?

2020-10-19 08:28 UTC, gnarea commented on src/main/kotlin/tech/relaycorp/relaynet/cogrpc/client/CogRPCClient.kt
> +                    logger.info("deliverCargo complete")
I'd suggest to combine these two and only have one log entry. Otherwise these would look like separate events.

2020-10-19 08:28 UTC, gnarea commented on src/main/kotlin/tech/relaycorp/relaynet/cogrpc/client/CogRPCClient.kt
> +                logger.info("deliverCargo complete")
Same as above: I'd suggest to combine these logs into one warning so they don't like separate events. E.g., `logger.log(Level.WARNING, "Ending deliverCargo due to ack error", t)`.

2020-10-26 16:01 UTC, sdsantos commented
Just pushed some more tests, it's not easy to test completeness, but we can test all scenarios and check if nothing unexpected was thrown.

And I did reproduce the issue and the checked the fix on a real device.

2020-10-27 09:59 UTC, gnarea approved these changes

2020-10-27 10:03 UTC, merged